In [6]:
import torch
torch.__version__




'1.12.0'

In [7]:
from torch.backends import  cudnn
import torch # 如果pytorch安装成功即可导入
print(torch.cuda.is_available()) # 查看CUDA是否可用
print(torch.cuda.device_count()) # 查看可用的CUDA数量
print(torch.version.cuda) # 查看CUDA的版本号
print(cudnn.is_available())  #返回True则说明已经安装了cuDNN

# ngpu= 1
# # Decide which device we want to run on
# device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
# print(device)
# print(torch.cuda.get_device_name(0))
# print(torch.rand(3,3).cuda())


True
1
11.3
True


In [35]:

### 维度基本信息获取

x = torch.tensor([[3,4,2],[5,6,2]])
print(x)
print(x.shape)

print(x.size)
print(x.size(0))
print(x.size(1))
print(x.numel())



tensor([[3, 4, 2],
        [5, 6, 2]])
torch.Size([2, 3])
<built-in method size of Tensor object at 0x00000253554C1B80>
2
3
6


In [43]:

### 基本矩阵形式生成

y = torch.arange(12)
print(y)
y = y.reshape(3,4)
print(y)

print(torch.zeros((3,4)))
print(torch.ones((3,4)))

# print(torch.ones(3,4)) 最好还是按照上面写

print(torch.randn((3,4))) #均值0，方差1的正态分布


print(torch.rand((3,4))) # 0-1 的随机数




tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.6327,  0.1593,  0.9833,  0.5491],
        [-0.4754,  1.0215,  0.1721, -0.5563],
        [-0.6483,  0.0429, -0.8140,  2.2393]])
tensor([[0.9413, 0.2452, 0.9980, 0.6155],
        [0.8583, 0.6249, 0.7188, 0.0359],
        [0.9448, 0.2964, 0.8423, 0.8615]])


In [ ]:
### 运算


























