In [1]:
import torch
torch.__version__

### 本节中习惯不好，以后张量最好用大写字体表示


'1.12.0'

In [3]:
from torch.backends import  cudnn
import torch # 如果pytorch安装成功即可导入
print(torch.cuda.is_available()) # 查看CUDA是否可用
print(torch.cuda.device_count()) # 查看可用的CUDA数量
print(torch.version.cuda) # 查看CUDA的版本号
print(cudnn.is_available())  #返回True则说明已经安装了cuDNN

# ngpu= 1
# # Decide which device we want to run on
# device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
# print(device)
# print(torch.cuda.get_device_name(0))
# print(torch.rand(3,3).cuda())


True
1
11.3
True


In [4]:

### 维度基本信息获取

x = torch.tensor([[3,4,2],[5,6,2]])
print(x)
print(x.shape)

print(x.size)
print(x.size(0))
print(x.size(1))
print(x.numel())



tensor([[3, 4, 2],
        [5, 6, 2]])
torch.Size([2, 3])
<built-in method size of Tensor object at 0x000002AD8CE9A130>
2
3
6


In [5]:

### 基本矩阵形式生成

y = torch.arange(12)
print(y)
y = y.reshape(3,4)
print(y)

print(torch.zeros((3,4)))
print(torch.ones((3,4)))

# print(torch.ones(3,4)) 最好还是按照上面写

print(torch.randn((3,4))) #均值0，方差1的正态分布


print(torch.rand((3,4))) # 0-1 的随机数


'''
torch.Tensor()
首先明确这一点,这是python类,是默认张量类型torch.FloatTensor()的别名,
每次调用torch.Tensor([1,2, 3, 4, 5])来构造一个tensor的时候,会调用Tensor类的构造函数,生成一个单精度浮点类型的张量。除此外还有别的构造方法但是很少用

但是torch.tensor(注意这里是小写)仅仅是python的函数,函数原型是

torch.tensor(data, dtype=None, device=None, requires_grad=False)
 其中data可以是:list,tuple,NumPy,ndarray等其他类型,torch.tensor会从data中的数据部分做拷贝(而不是直接引用),根据原始数据类型生成相应的torch.LongTensor torch.FloatTensor和torch.DoubleTensor

'''


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.2791, -1.0378, -1.1596, -0.8834],
        [ 1.8179,  0.4698,  0.1582,  1.0156],
        [-0.3633,  1.4958,  0.4013, -0.4824]])
tensor([[5.4174e-01, 9.9210e-01, 6.8271e-04, 7.5525e-01],
        [4.4803e-01, 4.0747e-01, 6.0206e-01, 8.2881e-01],
        [3.9961e-01, 4.9765e-01, 1.9458e-01, 9.6983e-01]])


In [6]:
### "按元素"运算

x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])

result = x+y,x-y,x*y,x/y,x**y

print(result)


print(torch.exp(x))


(tensor([ 3,  4,  6, 10]), tensor([-1,  0,  2,  6]), tensor([ 2,  4,  8, 16]), tensor([0.5000, 1.0000, 2.0000, 4.0000]), tensor([ 1,  4, 16, 64]))
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [7]:
### 张量连接

x = torch.arange(12,dtype = torch.float32).reshape(3,4)
y= torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])


print(torch.cat((x,y),dim=0)) #dim=0，轴0，行
#可以看作从外层开始数第几个括号，连接的张量不可以有缺
print(torch.cat((x,y),dim=1)) #dim=0，轴0，列



print(x==y)  ##逻辑判断矩阵

x.sum()


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


tensor(66.)

In [8]:

#广播机制

## 形状不同的张量进行运算

a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

print(a,b)
print(a+b)


tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [9]:
### 索引和切片

x = torch.arange(12,dtype = torch.float32).reshape(3,4)

print(x)
print(x[-1]) #最后一个元素（dim=0）
print(x[1:3])   # 1到2行（第1到2个元素 dim=0）
print(x[1,1:3])   # 第二行的第1到2个元素 dim=1

print(x[0:2, :])   # 第1到2行的所有元素，:表示所有






tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([5., 6.])
tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


In [10]:
x = torch.arange(12,dtype = torch.float32).reshape(3,4)
y= torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])


print(id(y) )

y = y + x #会重新给y分配内存地址
print(id(y) )


# 以下则不会
y += x
print(id(y) )

y[:] = y + x
print(id(y) )



2944414293264
2944415265312
2944415265312
2944415265312


In [19]:
### 与numpy对象相互转换
x = torch.arange(12,dtype = torch.float32).reshape(3,4)
y= torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

A = x.numpy()
print(A)

B = torch.tensor(A)
print(B)


A = torch.tensor(3.2)

print(A.item()) # .item()  can only convert an array of size 1 to a Python scalar

print(float(A))
print(int(A))

print(B.T) #矩阵转置


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
3.200000047683716
3.200000047683716
3
tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])


In [2]:
 print(dir(torch.distributions)) # 查看模块中所有函数和类

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'ContinuousBernoulli', 'CorrCholeskyTransform', 'CumulativeDistributionTransform', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'IndependentTransform', 'Kumaraswamy', 'LKJCholesky', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'MixtureSameFamily', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'OneHotCategoricalStraightThrough', 'Pareto', 'Poisson', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'ReshapeTransform', 'SigmoidTransform', 'SoftmaxTransform', 'SoftplusTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'TanhTransform', 'Transform', 'TransformedDistribution', 'Uniform', 'VonMises', 'Weib

In [3]:
help(torch.cumsum)

Help on built-in function cumsum in module torch:

cumsum(...)
    cumsum(input, dim, *, dtype=None, out=None) -> Tensor
    
    Returns the cumulative sum of elements of :attr:`input` in the dimension
    :attr:`dim`.
    
    For example, if :attr:`input` is a vector of size N, the result will also be
    a vector of size N, with elements.
    
    .. math::
        y_i = x_1 + x_2 + x_3 + \dots + x_i
    
    Args:
        input (Tensor): the input tensor.
        dim  (int): the dimension to do the operation over
    
    Keyword args:
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            If specified, the input tensor is casted to :attr:`dtype` before the operation
            is performed. This is useful for preventing data type overflows. Default: None.
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> a = torch.randn(10)
        >>> a
        tensor([-0.8286, -0.4890,  0.5155,  0.8443,  0.1865